language: ruby
env:
  global:
    secure: hHS/M9SzgIxGPfTXWxGBkIqsUNY01k1BnH1LChM3vE+549SexzrMJzj8IEywVdru7QvLrTpZlX86F4C939CRzM0rZ7gqxNb0BVgOfON8C9VmgnWWMpyCJYUzH8WsrjigXgU58dk7Szitqt2trP2mgnxq3fm+LLB9+MH6JsoXzpzgPODdcMjpWFyi438i+zSLtTyVQHAzIV4KHYcP951gg3pl3Tr7WSm/hbKVm5GFzej3pj0/C59Tw6qaSZojdcQXG4k/k98oy3Bzea95t4Ka9rh3EQRN8tAkl8av8W0itDvC2eqYdr9caTFoFhM4h3/onnF0/21bi40h4v7SlxFfpA4TxGvH6TWWABuRDTCpnuoGoL1IWO3sm9nWggPKhpADKVsXhg9pC9kM1PxHsoE6BW3XPS7sFcbOzHb1RGjhlPOHgCQKwegTCASEOBdWoDMluGLhB6pe4Vo/gxU7B1cG8Ep6dm7koxGYqrgED7UAmoDbQLLM42/fb8XY43CU121olhycXkq29I0Q3yl8jeAmt/DLI/TnbLVlKMZ2P4G+jmcSA+lcXxG72qZZhLqvWxW0fuGnZNEf1SzFM4RnXFRXV2r3/EHzXTNOla6Op1XrH8P8Qti860F91/Yna6HpyozvfSw0Xy8ivzdjSRlwQRXlIUwm3owxKRPd30/SLjV9z5s=
rvm:
  - 2.2.0
script:
  - bundle install
  - bundle exec rake spec
  - bundle exec rake package
deploy:
- provider: rubygems
  api_key:
    secure: kdCkFx4OZSiUTv3fB4goJKtRAFS2TtCn1Gjf1AGgRyUzFzX60D6F8psOKRPxtrOAY+tWRSKuKLq7O1PMtw4XvKmrzrAyPlPMP+U1xEN6dRESw7Tt9S3WCevk/9xE763wt735whPIcdt+SRwhk+5Mc4MSHc50+on7lmMwNLltsckvvE4KYV2OqXKqJqEoKzH31LqgPzEhP3B7TXISzHsCUmS8wxb2Dfd+srp/iRg3ycioqCWyqd1KRXPvwSKgyvu5EZDXWSdqS8/9HvX3qPqKfgFCbQSuzMToILh1JZGGhVYxpyxsqfE+pIcorGlhxB6HSB7hawqTtq4UdLkDXUojA0/HNnQ6xoGOcSNjHm2BLsN4Eb0ajK49n47kid8+Aj46WMAuGuUgXbnAZxVJyI4a4gd2jtDpqlMpjcfCbvBroIqnevNXf1y36A/WJybvA06Y8OdJwetXGerNppP3m9kZU/GZvS3uqVCGbY2mgbcbwEOnv4PQ5zNWhfvCShE6GE89Wpjno+5klLE4pS3603s7Z/VkDKCYOnWJlJDql7pChYPHrh4dcWbWRVe3+mTyOMet0jsYP/sktY/y8Ot0REvH39thkJ9GA8/pSeI/3Zm5nZQQ3kYEpMr8FOc2ACpbKbw0emHwdx3YleAYt15MXRQMfZF7F6xkc7OMCTZv6FzoLcQ=
  gem: pact-provider-verifier
  on:
    tags: true
    repo: pact-foundation/pact-provider-verifier
- provider: releases
  api_key:
    secure: AumB4WoeD8s03xt0Sb3QFTNnJOr+NJ1K6O0QLmeJnN/NNDTrItcChXJoTcPpEY51AQ8cO3ECtqjVtSNVsXdJyigJXGke5zAoJ/qA+hDTXSjI6YqWHqE+u515eNZiosfDxOih1Avqi8Vu4SB7/2vsvkqI69Zkw7unaorkzhuWrJxYHPdRCCdBOGF/WB9cGEeNtaB2zSVK7Giy+jqT9z74g6jIYJMkgmx8WVjBYqVhMLgOlet0DNWLcfZOtf3JINd5Slznhbnbli4u2Yf0ok1n3SxMwzwoVpZ+oQ5tFcRb3aRlg06fB7xOhwjd+V/5BKmLzPYaKPPq5MR4yk9+XHlnuvTyFnz0qs11Q8jRDc6FpJu8oUdlt1p5OAMU2MkOpQNdqB3SCmf4UNrGEyT9gTQFPGXQCngs+lrN0cP1QN17UXRO21PQZoyYh0QxP8IiAWc0n+cMBFZDnmzbuSMj+mTh3hWl1VvthCOG49XFHYBbEuU0J2FOi9UjP2oUz/aV0NUWTcNARf3eztDY8d60XI60kssEtIKB2XiH+ArDiGlTu6UTy8OGeLmv6xpJJv/CzjFlIrOBqNRy1mkiDpSlRypyihPqpfb5wukG8rDZfZjtfJXJGG/jH7r4CQS0ayvhN6McfqT+RJ3admYdD56k1mFHTVBPkQhnj1L6VR5e7XOQAO0=
  file: pkg/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: pact-foundation/pact-provider-verifier
    tags: true
after_deploy:
  - bundle exec rake generate_release_notes[$TRAVIS_TAG]
  - bundle exec rake upload_release_notes[$TRAVIS_REPO_SLUG,$TRAVIS_TAG]
